### ISSUE TITLE
create UML diagram

### ISSUE THREAD

**Issue by lukik45** [lukik45/PUT-SE-BuildingInfo#16]
### DoD 
- [x] The class model has been designed (for own classes, if more than 10 then only for the most important classes) using the UML class diagram and placed in the repository or the project wiki
- [ ] A sequence diagram illustrating the processing sequence of the selected operation starting from receiving the REST request to returning the value in the REST controller  !!**not graded if there are 4 members**

### Remarks
- the diagram should clearly show the implementation of design patterns

**Comment by Batukuju** [comment]
![obraz](https://user-images.githubusercontent.com/50993098/169718373-f1f969dc-5439-4254-bd4e-1c016f90f4ea.png)
