### ISSUE TITLE
Set up Sprint2 Backlog

### ISSUE THREAD

**Issue by bujowskis** [lukik45/PUT-SE-BuildingInfo#35]
- [x] add all needed issues
- [x] assign assignees
- [ ] add labor intensity estimates

**Comment by bujowskis** [comment]
Now I need you all to fill your labor intensity estimates and we can close this issue

**Comment by lukik45** [comment]
I 've filled mine

**Comment by bujowskis** [comment]
@Batukuju @white07S still waiting for your estimates

**Comment by bujowskis** [comment]
didn't notice it's all filled, closing
